mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.edu.spring.mybatis.model
  type-handlers-package: com.edu.spring.mybatis.handler
  generator:
    base-package: com.edu.spring
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    username: root
    password: 123456